"""Hand-written edge cases for Flo State's custom syntax + everyday note shapes."""
CUSTOM = [
    ("wiki basic", "See [[Some Page]] and [[Other|alias]] here.\n"),
    ("wiki heading", "[[Page#Heading]] and [[Page#^block]]\n"),
    ("wiki embed", "![[image.png]] and ![[Note]]\n"),
    ("wiki unclosed", "[[not closed and [[ok]]\n"),
    ("emoji", "hi :smile: and :not_a_real_emoji: :+1: :tada:\n"),
    ("dashes", "a -- b --- c ---- d\n-- start\nend --\n"),
    ("math inline", "Euler $e^{i\\pi}+1=0$ and $$x^2$$ inline\n"),
    ("math block", "$$\n\\int_0^1 x\\,dx\n$$\n\ntext\n"),
    ("math dollars", "costs $5 and $10 today\n"),
    ("frontmatter", "---\ntitle: Hello\ntags: [a, b]\n---\n# Body\n"),
    ("frontmatter unclosed", "---\ntitle: x\n# not closed\n"),
    ("frontmatter not first", "text\n---\ntitle: x\n---\n"),
    ("space dest link", "[label](my file.md) and [x](a b c.md \"title\")\n"),
    ("nested link", "[outer [inner](a)](b)\n"),
    ("escape", "\\*not em\\* and \\[x\\] \\# no\n"),
    ("html block", "<div>\nhello\n</div>\n\npara <span>x</span>\n"),
    ("html comment", "<!-- a comment -->\ntext\n"),
    ("table", "| a | b |\n|---|:-:|\n| 1 | 2 |\n| 3 | 4 |\n"),
    ("table no lead pipes", "a | b\n--|--\n1 | 2\n"),
    ("tasks", "- [ ] todo\n- [x] done\n  - [X] nested\n* [ ]  spaced\n"),
    ("strike", "~~gone~~ and ~single~ and ~~~three~~~\n"),
    ("autolink", "<https://a.com> and https://b.com/x?y=1 and www.c.com\n"),
    ("mixed lists", "- a\n- b\n  1. one\n  2. two\n     - deep\n- c\n"),
    ("list interrupt", "foo\n* bar\n* baz\n\nqux\n1. one\n2. two\n"),
    ("ordered start", "3. three\n4. four\n\n1) paren\n2) paren\n"),
    ("empty items", "-\n- \n-  x\n*\n"),
    ("loose list", "- a\n\n- b\n\n  para in b\n- c\n"),
    ("headings", "# H1\n## H2\n### H3\n#### H4\n##### H5\n###### H6\n####### seven\n#nospace\n"),
    ("setext", "Title\n=====\n\nSub\n---\n"),
    ("heading trailing hashes", "## Heading ##\n# #\n#\n"),
    ("emphasis mix", "***both*** **bold *nested em* bold** _u_ __uu__ *a **b** c*\n"),
    ("emphasis trailing space", "**this ** and *that *\n"),
    ("intraword", "snake_case_word and foo*bar*baz\n"),
    ("code spans", "`one` ``two ` two`` ```x```\n"),
    ("fenced", "```js\nconst a = 1;\n```\n\n~~~\nplain\n~~~\n"),
    ("fenced unclosed", "```python\nprint(1)\n"),
    ("indented code", "para\n\n    code line\n    more\n"),
    ("blockquote", "> quote\n> > nested\n>\n> - list in quote\n"),
    ("hr variants", "---\n***\n___\n- - -\n"),
    ("hard breaks", "line one  \nline two\\\nline three\n"),
    ("images", "![alt](img.png) ![alt2](img 2.png \"t\") ![](x)\n"),
    ("link ref", "[a][ref] and [ref]\n\n[ref]: https://x.com \"Title\"\n"),
    ("entities", "&amp; &copy; &#123; &nope;\n"),
    ("unicode", "📓 Master — naïve café 日本語 🎉 emoji\n- • bullet char\n"),
    ("crlf", "a\r\nb\r\n- c\r\n"),
    ("tabs", "-\titem\n\t- nested tab\n"),
    ("date headings", "## 2026.01.02\n\n### Jane Doe (beta user, interview)\n\n* Also uses a competitor\n* Likes the layout better\n"),
    ("empty", ""),
    ("only newline", "\n"),
    ("no trailing newline", "# Title\n\n- item"),
    ("long line", "word " * 300 + "\n"),
    ("deep nesting", "".join("  " * i + "- level %d\n" % i for i in range(10))),
    ("mixed markers", "- a\n* b\n+ c\n"),
    ("numbered big", "".join(f"{i}. item {i}\n" for i in range(1, 25))),
    ("quote list code", "> ```\n> code\n> ```\n"),
    ("html inline", "a <b>bold</b> <br/> c\n"),
    ("link in heading", "## [link](x) **bold** heading\n"),
    ("emphasis across lines", "*start\nend*\n"),
    ("bracket noise", "[ ] [x] [] [[]] ]]\n"),
    ("colon noise", "time 10:30:45 :: :a: ::\n"),
]

# block renderings: code languages, tables, math, mermaid, html
CODE_SAMPLES = {
    "js": 'import x from "y";\nconst re = /a+b/g, n = 0x1F, s = `t ${n}`;\n// line\nclass A extends B { #p = 1; static m(a, ...r) { return this?.p ?? null; } }\nasync function* g() { yield await f(true); }\n',
    "ts": 'interface P<T> { a?: T; readonly b: number }\ntype U = "x" | keyof P<string>;\nenum E { A = 1 }\nexport const f = <T,>(v: T): T => v as T;\n@dec class C implements P<number> { constructor(private b: number) {} }\n',
    "jsx": 'const el = <div className="x" onClick={() => go(1)}>Hi {name}</div>;\n',
    "tsx": 'export function App({ a }: { a: string }) { return <Foo bar={a} />; }\n',
    "json": '{\n  "a": 1, "b": [true, false, null], "c": {"d": "e\\n"}, "f": -1.5e3\n}\n',
    "python": '@decorator\ndef f(x: int = 1, *a, **k) -> str:\n    """doc"""\n    return f"v={x!r}" if x else None  # comment\nclass K(Base):\n    async def m(self): await g(lambda y: y ** 2)\n',
    "bash": '#!/bin/bash\nfor f in *.md; do echo "$f ${HOME}" | grep -v x > /dev/null; done\nif [ -z "$1" ]; then exit 1; fi # c\n',
    "sh": 'export A=1 && ls -la ~/x\n',
    "shell": 'cd /tmp; VAR=$(pwd)\n',
    "swift": 'import AppKit\n@MainActor final class V: NSView {\n    private var x: Int? = nil // c\n    func f<T>(_ a: T) throws -> [String: Int] { guard let y = x else { return [:] }; return ["a": y] }\n}\nlet s = "a \\(b)"\n',
    "rust": 'use std::io;\n#[derive(Debug)]\npub struct S<\'a> { x: &\'a str }\nfn main() -> Result<(), Box<dyn Error>> { let mut v = vec![1u8, 2]; println!("{}", v.len()); Ok(()) }\n',
    "go": 'package main\nimport "fmt"\nfunc main() { x := map[string]int{"a": 1}; for k, v := range x { fmt.Println(k, v) } }\n',
    "css": '@media (max-width: 600px) { .a > #b:hover::before { color: #fff !important; margin: 0 1.5em; content: "x"; } }\n:root { --v: calc(100% - 2px); }\n',
    "html": '<!DOCTYPE html>\n<html lang="en"><head><style>p { color: red }</style></head>\n<body><!-- c --><p class="x">Hi &amp; bye</p><script>let a = 1;</script></body></html>\n',
    "yaml": 'key: value\nlist:\n  - a\n  - "b"\nnum: 1.5 # c\nanchor: &x { a: true }\n',
    "sql": 'SELECT a.id, COUNT(*) AS n FROM users a LEFT JOIN t ON t.x = a.id WHERE a.name LIKE \'%x%\' GROUP BY 1; -- c\n',
    "markdown": '# Title\n\n**bold** and *em* and `code`\n- item\n> quote\n',
    "java": 'public class A { public static void main(String[] args) { System.out.println("x" + 1); } }\n',
    "c": '#include <stdio.h>\nint main(void) { printf("%d\\n", 42); return 0; }\n',
    "cpp": 'template<typename T> auto f(T&& x) -> decltype(x) { return std::move(x); }\n',
    "ruby": 'def f(x) = x * 2\nputs :sym, "s#{1}" # c\n',
    "diff": '--- a\n+++ b\n@@ -1 +1 @@\n-old\n+new\n',
    "toml": '[a]\nb = "c"\nd = 1\n',
    "unknownlang": 'just text here\n',
    "JS": 'const upper = 1;\n',
    "py title=x.py": 'print(1)\n',
}
for lang, code in CODE_SAMPLES.items():
    CUSTOM.append((f"code {lang}", f"Intro\n\n```{lang}\n{code}```\n\nafter\n"))
CUSTOM += [
    ("code in quote", "> ```js\n> const a = 'x'; // c\n> ```\n"),
    ("code in list", "- item\n  ```python\n  def f(): pass\n  ```\n"),
    ("code tilde", "~~~rust\nfn x() {}\n~~~\n"),
    ("code unclosed lang", "```js\nlet a = 1\n"),
    ("html tags inline", "text <span class=\"a\">x</span> <img src=\"a.png\" alt='b'/> &amp; <!-- c -->\n"),
    ("html block attrs", "<div class=\"note\" data-x='1'>\n  <p>para <b>bold</b></p>\n</div>\n\ntext\n"),
    ("html details", "<details>\n<summary>Sum</summary>\n\nBody **md**\n</details>\n\nafter\n"),
    ("frontmatter types", "---\ntitle: \"Hello\"\ncount: 3\ndraft: true\ntags:\n  - a\n  - b\n---\n# Body\n"),
    ("table rich", "| Name | Qty | Notes |\n|:--|:-:|--:|\n| **Apple** | 3 | `fresh` and [link](x) |\n| Pear | 12 | ~~old~~ *soft* |\n\nafter\n"),
    ("table wide", "| Col | Long |\n|---|---|\n| a | " + "word " * 40 + "|\n\nafter\n"),
    ("mermaid", "Intro\n\n```mermaid\ngraph TD\n  A[Start] --> B{Ok?}\n  B -->|yes| C[Done]\n```\n\nafter\n"),
    ("math display", "Intro\n\n$$\nE = mc^2\n$$\n\nand $a^2 + b^2 = c^2$ inline, $\\frac{1}{2}$.\n"),
]
