"""Locations shared by the oracle scripts. Nothing here is machine-specific:

- WRITER_REPO      checkout of https://github.com/joelbqz/writer-computer
                   (default: a sibling of this repo, ../writer-computer)
- ORACLE_SANDBOX   workspace the mock backend serves (default: oracle/sandbox/Sample,
                   generated by make_sandbox.py)
- ORACLE_TMP       scratch/output directory (default: <system temp>/flo-oracle)
- NATIVE           FloStateNative binary to compare against (default: the most
                   recently built debug binary under the repo's build dirs)
"""
import os
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
FIXTURES = ROOT / "fixtures"

WRITER_REPO = Path(os.environ.get("WRITER_REPO", ROOT.parent / "writer-computer")).expanduser().resolve()
DIST = WRITER_REPO / "apps" / "desktop" / "dist"
SCHEMA = WRITER_REPO / "apps" / "desktop" / "shared" / "settings.schema.json"

SANDBOX = Path(os.environ.get("ORACLE_SANDBOX") or os.environ.get("FLO_SANDBOX")
               or HERE / "sandbox" / "Sample").expanduser().resolve()

TMP = Path(os.environ.get("ORACLE_TMP", Path(tempfile.gettempdir()) / "flo-oracle"))


def tmpdir(name=""):
    """A scratch directory under ORACLE_TMP (created)."""
    p = TMP / name if name else TMP
    p.mkdir(parents=True, exist_ok=True)
    return p


def native_binary():
    if os.environ.get("NATIVE"):
        return Path(os.environ["NATIVE"])
    candidates = [ROOT / d / "debug" / "FloStateNative"
                  for d in (".build", ".iso/.build", ".build-shell", ".build-main", ".build-lead")]
    existing = [c for c in candidates if c.exists()]
    if not existing:
        raise SystemExit("FloStateNative not built: run `swift build --product FloStateNative` (or set NATIVE=path)")
    return max(existing, key=lambda c: c.stat().st_mtime)


def ensure_sandbox():
    """Generate the sample workspace on first use (only for the default location)."""
    if not SANDBOX.exists() and SANDBOX == (HERE / "sandbox" / "Sample").resolve():
        import make_sandbox
        make_sandbox.main()
    if not SANDBOX.is_dir():
        raise SystemExit(f"oracle sandbox {SANDBOX} missing (run oracle/make_sandbox.py or set ORACLE_SANDBOX)")
    return SANDBOX
